config/routes.rb
Rails.application.routes.draw do

  root "sessions#new"
  get "users" => "users#index"
  get "users/new" => "users#new"
  post "users" => "users#create"
  get "users/:id" => "users#show", as: :user

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"

  get "users/:id/notes" => "notes#index"
  get "users/:id/notes/new" => "notes#new", as: :new_user_note
  post "users/:id/notes/new" => "notes#create"
  delete "users/:id/notes/new" => "notes#destroy", as: :delete_note

  get "users/:id/pictures" => "pictures#index"
  get "users/:id/pictures/new" => "pictures#new", as: :new_user_picture
  post "users/:id/pictures/new" => "pictures#create"
  delete "users/:id/pictures/new" => "pictures#destroy", as: :delete_picture

  

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :notes
	has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def authenticate
  	unless logged_in?
  		flash[:error] = "You must be logged in to access this section of the site"
      redirect_to login_url
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	def index
		@notes = Note.all 
	end
	def show
		@user = User.find(params[:id])
		@notes = Note.where(user_id: @user.id)
	end
	def create
		# new_user = User.create(user_params)
		@note = Note.create(user_params)
		if @note.save
			current_user.notes << @note
			redirect_to user_path
		end
	end
	def new
		# @user = User.new
		@note = Note.new
	end


	def edit
		@user = User.find(params[:id])
	end
	def update
		note = Note.find(params[:id])
		note.update(user_params)
		redirect_to user_path(user)
	end
	def destroy
		note = Note.find(params[:id])
		note.destroy
		redirect_to user_path
	end

	private 

	def user_params
		params.require(:note).permit(:title, :list)
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	def index
		@pictures = Picture.all 
	end
	def show
		#@user = User.find(params[:id])
		#@pictures = Picture.where(user_id: @user.id)
	end
	def create
		#new_user = User.create(user_params)
		#redirect_to user_path(new_user)
		@picture = Picture.create(picture_params)
		if @picture.save
			current_user.pictures << @picture
			redirect_to user_path
		end
	end
	def new
		@picture = Picture.new
	end
	def edit
		#@user = User.find(params[:id])
	end
	def update
		#user = User.find(params[:id])
		#user.update(user_params)
		#redirect_to user_path(user)
	end
	def destroy
		@picture = current_user.pictures.find(params[:id])
		@picture.destroy
		redirect_to user_path
	end

	private 

	def set_picture
		@picture = Picture.find(params[:id])
	end
	def picture_params
		params.require(:picture).permit(:title, :caption, :image)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end
	def create
		user = User.find_by(email: params[:login][:email].downcase)
		if user && user.authenticate(params[:login][:password])
			session[:user_id] = user.id.to_s
			redirect_to user_path(user)
		else
			render :new
		end
	end
	def destroy
		session.delete(:user_id)
		redirect_to login_path, notice: "LOGGED OUT"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper
	def index
		@users = User.all
	end
	def show
		@user = current_user
		#@notes = @user.notes
		#@pictures = @user.pictures
	end
	def new
		@user = User.new
	end

	def create
		name = user_params[:name]
		email = user_params[:email]
		digest = user_params[:password]

		@user = User.new({name:name, email:email, password: digest})
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to user_path(:user)
		else
			render :new
		end 
	end

	private
	def user_params
		params.require( :user ).permit( :name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">GoogleKeep</a>
    </div>

  
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Googlekeep</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>

<div class="container">
	<%= yield %>
</div>	

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for :note do |f| %>
  <% if @note.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@note.errors.count, "error") %> prohibited
        this note from being saved:</h2>
    <ul>
    <% @note.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :list %><br />
    <%= f.text_area :list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/new.html.erb
<h1>New Note</h1>
<%= render 'form' %>
<%= link_to 'BACK', user_path %>

app/views/pictures/_form.html.erb
<%= form_for :picture do |f| %>
  <% if @picture.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited
          this picture from being saved:</h2>
      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :list %><br />
    <%= f.text_area :list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>
<%= form_for :picture do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br><br>
	
	<%= f.label :image %>
	<%= f.file_field :image %>
	<br><br>
	<%= f.submit %> 

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
	<% @users.each do |user| %>
		<li><%= user.name %></li>
	<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up Page</h1>

<%= form_for @user do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :email %>
		<%= f.email_field :email %>
	</div>
	<div>
		<%= f.label :password %>
		<%= f.password_field :password %> 
	</div>
	<div> 
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>

	<%= f.submit %>
	
<% end %>

app/views/users/show.html.erb
<h1> welcome <%= current_user.name %>!</h1>

 
 <p>This is inspired by GoogleKeep. Feel free to use this as a way to save your thoughts online so that they are accessible whenever you need them. </p> 

<% @user.notes.each do |note| %>
	<div class="jumbotron bg-warning" > 
	<p class="bg-info"><%= note.title %></p>
	<p class="bg-warning"><%= note.list %></p>
	<br>
	<%= link_to 'DELETE', delete_note_path(note.id), method: :delete, data: { confirm: 'Are you sure?' } %>
	<br>
	</div>
<% end %> 

<% @user.pictures.each do |post| %>
    <%= picture.title %><br>
    <%= image_tag post.image.url(:large) %><br><hr>
    <%= link_to 'DELETE', delete_picture_path(picture.id), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<br><br>

<%= link_to "CREATE A NEW NOTE", new_user_note_path(@user) %>
<%= link_to "UPLOAD A PICTURE" , new_user_picture_path(@user) %>



<br><br>
<%= link_to 'Log Out', logout_path, method: :delete %>